"""Collect every measured number into results.json and a LaTeX macro file.

The macro file is the link between the code and the manuscript: every value the paper
prints is defined once here, from a measured artefact, so a number in the text cannot
drift away from the run that produced it.

    python scripts/10_export_paper_values.py
    # then in paper.tex:  \input{results/paper_values.tex}
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import _bootstrap  # noqa: F401
from _bootstrap import REPO_ROOT, RESULTS

from osteognn.utils import load_json, save_json

PCT = lambda x: f"{100 * x:.2f}"          # noqa: E731
F4 = lambda x: f"{x:.4f}"                 # noqa: E731


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="full")
    args = parser.parse_args()

    bundle: dict = {}
    lines = ["% Generated by scripts/10_export_paper_values.py -- do not edit by hand.\n",
             "% Every macro below is a measured value from results/.\n\n"]

    # -- dataset -------------------------------------------------------------------
    path = RESULTS / "dataset_summary.json"
    if path.exists():
        data = load_json(path)
        bundle["dataset"] = data
        for part in ("train", "val", "test"):
            lines.append(macro(f"N{part.capitalize()}", data["totals"][part]))
        lines.append(macro("NTrainAug", data["processed"]["train"]["total"]))

    # -- intensity analysis --------------------------------------------------------
    path = RESULTS / "intensity_analysis.json"
    if path.exists():
        data = load_json(path)
        bundle["intensity"] = data
        short = {"Normal": "Normal", "Osteopenia": "Openia", "Osteoporosis": "Oporosis"}
        for name, stats in data["per_class"].items():
            lines.append(macro(f"Bone{short[name]}Mean", f"{stats['bone_mean']:.2f}"))
            lines.append(macro(f"Bone{short[name]}SD", f"{stats['bone_sd']:.2f}"))
            lines.append(macro(f"Whole{short[name]}Mean", f"{stats['mean']:.2f}"))
            lines.append(macro(f"Whole{short[name]}SD", f"{stats['sd']:.2f}"))
        k = data["kruskal_bone"]
        lines.append(macro("KruskalH", f"{k['H']:.1f}"))
        lines.append(macro("KruskalP", f"{k['p']:.1e}".replace("e-", "\\times 10^{-")
                           .replace("+", "") + "}"))
        lines.append(macro("KruskalEps", f"{k['epsilon_squared']:.3f}"))

    # -- main run ------------------------------------------------------------------
    path = RESULTS / f"run_{args.run}.json"
    if path.exists():
        run = load_json(path)
        test, training = run["test"], run["training"]
        bundle["test"] = test
        bundle["training"] = {k: v for k, v in training.items() if k != "history"}
        bundle["environment"] = run.get("environment", {})

        lines.append("\n% --- headline test metrics ---\n")
        lines.append(macro("TestAcc", PCT(test["accuracy"])))
        lines.append(macro("TestAccLo", PCT(test["accuracy_ci"][0])))
        lines.append(macro("TestAccHi", PCT(test["accuracy_ci"][1])))
        lines.append(macro("TestPrec", F4(test["precision_macro"])))
        lines.append(macro("TestRec", F4(test["recall_macro"])))
        lines.append(macro("TestFOne", F4(test["f1_macro"])))
        lines.append(macro("TestAUC", F4(test["auc_macro_ovr"])))
        lines.append(macro("TestTopTwo", PCT(test["top2_accuracy"])))
        lines.append(macro("TestQWK", F4(test["qwk"])))
        lines.append(macro("TestMAE", F4(test["mae_grade"])))
        lines.append(macro("TestECE", F4(test["calibration"]["ece"])))
        short = {"Normal": "Normal", "Osteopenia": "Openia", "Osteoporosis": "Oporosis"}
        for name, stats in test["per_class"].items():
            tag = short[name]
            lines.append(macro(f"AUC{tag}", F4(stats["auc"])))
            lines.append(macro(f"Prec{tag}", F4(stats["precision"])))
            lines.append(macro(f"Rec{tag}", F4(stats["recall"])))
            lines.append(macro(f"FOne{tag}", F4(stats["f1"])))
            lines.append(macro(f"RecLo{tag}", f"{stats['recall_ci'][0]:.3f}"))
            lines.append(macro(f"RecHi{tag}", f"{stats['recall_ci'][1]:.3f}"))
            lines.append(macro(f"Support{tag}", stats["support"]))
        err = test["error_structure"]
        lines.append(macro("NCorrect", err["correct"]))
        lines.append(macro("NErrors", err["errors"]))
        lines.append(macro("NAdjacent", err["adjacent"]))
        lines.append(macro("NExtreme", err["extreme"]))
        lines.append(macro("PctExtremeOfErrors",
                           f"{100 * err['extreme'] / max(1, err['errors']):.0f}"))

        lines.append("\n% --- training behaviour ---\n")
        history = training["history"]
        lines.append(macro("EpochsRun", training["epochs_run"]))
        lines.append(macro("BestEpoch", training["best"]["epoch"]))
        lines.append(macro("TrainAccFirst", PCT(history[0]["train_acc"])))
        lines.append(macro("TrainAccLast", PCT(history[-1]["train_acc"])))
        lines.append(macro("ValAccFirst", PCT(history[0]["val_acc"])))
        lines.append(macro("ValAccBest", PCT(training["best"]["val_acc"])))
        lines.append(macro("ValFOneBest", PCT(training["best"]["val_macro_f1"])))
        lines.append(macro("TrainLossFirst", f"{history[0]['train_loss']:.2f}"))
        lines.append(macro("TrainLossLast", f"{history[-1]['train_loss']:.2f}"))
        lines.append(macro("ValLossFirst", f"{history[0]['val_loss']:.2f}"))
        lines.append(macro("ValLossBest", f"{training['best']['val_loss']:.2f}"))
        gap = 100 * (history[-1]["train_acc"] - history[-1]["val_acc"])
        lines.append(macro("TrainValGap", f"{gap:.2f}"))

    # -- efficiency ----------------------------------------------------------------
    path = RESULTS / "efficiency.json"
    if path.exists():
        eff = load_json(path)
        bundle["efficiency"] = eff
        lines.append("\n% --- computational cost ---\n")
        lines.append(macro("ParamsTotal", f"{eff['total_parameters']:,}"))
        lines.append(macro("ParamsTrainable", f"{eff['trainable_parameters']:,}"))
        lines.append(macro("ParamsM", f"{eff['parameters_millions']:.2f}"))
        lines.append(macro("ParamsTrainablePct",
                           f"{100 * eff['trainable_fraction']:.1f}"))
        lines.append(macro("GMACs", f"{eff['macs']['gmacs']:.2f}"))
        lines.append(macro("GFLOPs", f"{eff['macs']['gflops']:.2f}"))
        if "latency_gpu" in eff:
            lines.append(macro("LatGPU", f"{eff['latency_gpu']['median_ms']:.1f}"))
            lines.append(macro("LatGPUTTA", f"{eff['latency_gpu_tta']['median_ms']:.1f}"))
            lines.append(macro("PeakMem", f"{eff['peak_memory']['peak_mb']:.0f}"))
            lines.append(macro("GPUName", eff.get("gpu_name", "")))
        lines.append(macro("LatCPU", f"{eff['latency_cpu']['median_ms']:.0f}"))
        for key, value in (eff.get("components") or {}).items():
            lines.append(macro(f"Params{key.title().replace('_','')}",
                               f"{value / 1e6:.2f}"))

    # -- ablation, baselines, sweep, seeds, xai ------------------------------------
    for name, key in (("ablation.json", "ablation"), ("baselines.json", "baselines"),
                      ("fusion_sweep.json", "fusion_sweep"),
                      ("multiseed.json", "multiseed"),
                      ("explainability.json", "explainability")):
        path = RESULTS / name
        if path.exists():
            bundle[key] = load_json(path)

    if "ablation" in bundle:
        # The manuscript names the variants by roman numeral; the artefact keys them
        # by the config section each one changes. Map once, here, so the table cells
        # and the prose cannot disagree about which row is which.
        lines.append("\n% --- ablation variants ---\n")
        for key, tag in (("full", "Full"), ("no_gcn", "NoGcn"), ("no_aux", "NoAux"),
                         ("mean_pool", "MeanPool"), ("no_clahe", "NoClahe"),
                         ("no_balance", "NoBalance"), ("no_tta", "NoTta"),
                         ("conv_control", "ConvControl")):
            row = bundle["ablation"].get(key)
            if not row:
                continue
            test = row["test"]
            lines.append(macro(f"Abl{tag}Acc", PCT(test["accuracy"])))
            lines.append(macro(f"Abl{tag}FOne", F4(test["f1_macro"])))
            lines.append(macro(f"Abl{tag}AUC", F4(test["auc_macro_ovr"])))
            # Signed deltas against the full model, so the sign is never hand-typed.
            base = bundle["ablation"]["full"]["test"]
            lines.append(macro(f"Abl{tag}DeltaAcc",
                               f"{100 * (test['accuracy'] - base['accuracy']):+.2f}"))
            lines.append(macro(f"Abl{tag}DeltaFOne",
                               f"{test['f1_macro'] - base['f1_macro']:+.4f}"))

    if "baselines" in bundle:
        lines.append("\n% --- baselines under the identical protocol ---\n")
        for key, tag in (("effb0_gap_fc", "Effb"), ("resnet50", "Resnet"),
                         ("densenet121", "Densenet"), ("vgg19", "Vgg"),
                         ("proposed", "Proposed")):
            row = bundle["baselines"].get(key)
            if not row:
                continue
            test = row["test"]
            lines.append(macro(f"Base{tag}Acc", PCT(test["accuracy"])))
            lines.append(macro(f"Base{tag}FOne", F4(test["f1_macro"])))
            lines.append(macro(f"Base{tag}AUC", F4(test["auc_macro_ovr"])))
            params = test.get("parameters")
            if params:
                lines.append(macro(f"Base{tag}Params", f"{params / 1e6:.2f}"))
            paired = row.get("mcnemar_vs_proposed")
            if paired:
                lines.append(macro(f"Base{tag}P", f"{paired['p_value']:.4f}"))
                lines.append(macro(f"Base{tag}Disc", paired["n_discordant"]))

    if "multiseed" in bundle:
        lines.append("\n% --- across-seed variability ---\n")
        for metric, tag in (("accuracy", "Acc"), ("f1_macro", "FOne"),
                            ("auc_macro_ovr", "AUC")):
            stats = bundle["multiseed"]["summary"][metric]
            fmt = PCT if metric == "accuracy" else F4
            lines.append(macro(f"Seed{tag}Mean", fmt(stats["mean"])))
            lines.append(macro(f"Seed{tag}SD", fmt(stats["sd"])))
            lines.append(macro(f"Seed{tag}Min", fmt(stats["min"])))
            lines.append(macro(f"Seed{tag}Max", fmt(stats["max"])))
        lines.append(macro("NSeeds", len(bundle["multiseed"]["seeds"])))
        # LaTeX control sequences are letters only, so a seed of 42 cannot appear in
        # a macro name as digits -- spell it out.
        words = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
                 "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
        spell = lambda s: "".join(words[c] for c in str(s))  # noqa: E731
        for seed, value in bundle["multiseed"]["summary"]["accuracy"]["per_seed"].items():
            lines.append(macro(f"SeedAccS{spell(seed)}", PCT(value)))

        # Fixed-seed replication gap. run_full and run_seed42 use the same seed and,
        # as asserted below, the same test partition, so any difference between them
        # is run-to-run nondeterminism alone -- the floor beneath which no ablation
        # delta can be interpreted. Computed here rather than quoted, because the
        # comparison is only meaningful if the partitions really are identical.
        pred_a = RESULTS / f"predictions_{args.run}.npz"
        pred_b = RESULTS / "predictions_seed42.npz"
        run_b = RESULTS / "run_seed42.json"
        if pred_a.exists() and pred_b.exists() and run_b.exists():
            import numpy as np
            a, b = np.load(pred_a), np.load(pred_b)
            if np.array_equal(a["labels"], b["labels"]):
                acc_a = bundle["test"]["accuracy"]
                acc_b = load_json(run_b)["test"]["accuracy"]
                agree = int((a["proba"].argmax(1) == b["proba"].argmax(1)).sum())
                lines.append(macro("ReplicaAccA", PCT(acc_a)))
                lines.append(macro("ReplicaAccB", PCT(acc_b)))
                lines.append(macro("ReplicaGap", f"{100 * abs(acc_a - acc_b):.2f}"))
                lines.append(macro("ReplicaDisagree", len(a["labels"]) - agree))
            else:
                print("  note: seed-42 partitions differ; replication gap not exported")

    if "fusion_sweep" in bundle:
        sweep = bundle["fusion_sweep"]
        lines.append("\n% --- fusion-weight sensitivity ---\n")
        lines.append(macro("BestW", f"{sweep['best_w']:.1f}"))
        lines.append(macro("SweepAccLo", PCT(sweep["test_accuracy_range"][0])))
        lines.append(macro("SweepAccHi", PCT(sweep["test_accuracy_range"][1])))
        lines.append(macro("SweepFOneDelta", F4(sweep["test_f1_delta"])))

    if "explainability" in bundle:
        lines.append("\n% --- explanation faithfulness ---\n")
        for method, tag in (("gradcam", "CAM"), ("gnnexplainer", "GNN"),
                            ("random_control", "Rand")):
            values = bundle["explainability"]["faithfulness"].get(method)
            if values:
                lines.append(macro(f"Del{tag}", F4(values["deletion_auc_mean"])))
                lines.append(macro(f"Ins{tag}", F4(values["insertion_auc_mean"])))

    save_json(bundle, RESULTS / "results.json")
    (RESULTS / "paper_values.tex").write_text("".join(lines), encoding="utf-8")
    n_macros = sum(1 for line in lines if line.startswith("\\newcommand"))
    print(f"wrote {RESULTS/'results.json'}")
    print(f"wrote {RESULTS/'paper_values.tex'}  ({n_macros} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
